services:
  redmine:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RAILS_ENV=development
      - SKIP_INITIAL_SETUP=false  # set to true to skip initial setup
      - RUN_CHOWN=true # set to true to change owner of files accordingly
    ports:
      - 9999:3000
    volumes:
      - ./redmine/files:/usr/src/redmine/files
      - ./redmine/sqlite:/usr/src/redmine/sqlite
      - ./redmine/plugins:/usr/src/redmine/plugins
      - ./redmine/themes/:/usr/src/redmine/themes
      - ./redmine/config/configuration.yml:/usr/src/redmine/config/configuration.yml