services:
  redmine:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9999:3000
    volumes:
      - ./redmine/files:/usr/src/redmine/files
      - ./redmine/sqlite:/usr/src/redmine/sqlite
      - ./redmine/plugins:/usr/src/redmine/plugins
      - ./redmine/themes/:/usr/src/redmine/themes
      # - ./redmine/config/configuration.yaml:/usr/src/redmine/config/configuration.yaml